import json
import csv

bundles = [
    # ===== TRAIN SIM WORLD (TSW1 / 2017) =====
    {
        "tsw_version": "TSW1",
        "bundle_id": None,
        "bundle_name": "Train Sim World: Standard Edition",
        "steam_url": "https://store.steampowered.com/app/503530/Train_Sim_World/",
        "bundle_type": "Edition",
        "price_usd": 39.99,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": ["Train Sim World", "CSX Heavy Haul: Sand Patch Grade Route"],
    },
    {
        "tsw_version": "TSW1",
        "bundle_id": None,
        "bundle_name": "Train Sim World: Digital Deluxe Edition",
        "steam_url": "https://store.steampowered.com/app/503530/Train_Sim_World/",
        "bundle_type": "Edition",
        "price_usd": 59.99,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World",
            "CSX Heavy Haul: Sand Patch Grade Route",
            "DB BR 155",
            "Rapid Transit",
            "Clinchfield Railroad: Elkhorn City - Dante",
        ],
    },
    # ===== TRAIN SIM WORLD 2020 =====
    {
        "tsw_version": "TSW2020",
        "bundle_id": "sub/377757",
        "bundle_name": "Train Sim World 2020: Deluxe Edition",
        "steam_url": "https://store.steampowered.com/sub/377757/",
        "bundle_type": "Edition",
        "price_usd": 49.99,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 2020",
            "Peninsula Corridor: San Jose - San Francisco Route Add-On",
            "Hauptstrecke Rhein-Ruhr: Duisburg - Bochum Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW2020",
        "bundle_id": "sub/692108",
        "bundle_name": "Train Sim World 2020 Collector's Edition",
        "steam_url": "https://store.steampowered.com/sub/692108/",
        "bundle_type": "Edition",
        "price_usd": 79.99,
        "discount_pct": 70,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 2020",
            "Long Island Rail Road: New York - Hicksville Route Add-On",
            "Main Spessart Bahn: Aschaffenburg - Gemünden Route Add-On",
            "Northern Trans-Pennine: Manchester - Leeds Route Add-On",
            "Peninsula Corridor: San Jose - San Francisco Route Add-On",
            "Hauptstrecke Rhein-Ruhr: Duisburg - Bochum Route Add-On",
        ],
    },
    # ===== TRAIN SIM WORLD 2 =====
    {
        "tsw_version": "TSW2",
        "bundle_id": "sub/490384",
        "bundle_name": "Train Sim World 2: Collector's Edition",
        "steam_url": "https://store.steampowered.com/sub/490384/",
        "bundle_type": "Edition",
        "price_usd": 79.99,
        "discount_pct": 25,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 2",
            "East Coastway: Brighton - Eastbourne & Seaford Route Add-On",
            "Hauptstrecke Rhein-Ruhr: Duisburg - Bochum Route Add-On",
            "Peninsula Corridor: San Jose - San Francisco Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW2",
        "bundle_id": None,
        "bundle_name": "Train Sim World 2: Standard Edition",
        "steam_url": "https://store.steampowered.com/app/1282590/Train_Sim_World_2/",
        "bundle_type": "Edition",
        "price_usd": 29.99,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 2",
            "Bakerloo Line: London Underground Route Add-On",
            "Spirit of Steam: Liverpool Lime Street - Crewe",
            "Hauptstrecke Hamburg - Lübeck Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW2",
        "bundle_id": None,
        "bundle_name": "Train Sim World 2: Deluxe Edition",
        "steam_url": "https://store.steampowered.com/app/1282590/Train_Sim_World_2/",
        "bundle_type": "Edition",
        "price_usd": 49.99,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 2",
            "Bakerloo Line: London Underground Route Add-On",
            "Spirit of Steam: Liverpool Lime Street - Crewe",
            "Hauptstrecke Hamburg - Lübeck Route Add-On",
            "East Coastway: Brighton - Eastbourne & Seaford Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW2",
        "bundle_id": None,
        "bundle_name": "TSW2: Rush Hour Deluxe Edition",
        "steam_url": "https://store.steampowered.com/app/1282590/Train_Sim_World_2/",
        "bundle_type": "Edition",
        "price_usd": 59.99,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 2",
            "Bakerloo Line: London Underground Route Add-On",
            "Spirit of Steam: Liverpool Lime Street - Crewe",
            "Hauptstrecke Hamburg - Lübeck Route Add-On",
            "London Commuter: London Victoria - Brighton Route Add-On",
            "Cathcart Circle Line: Glasgow - Newton & Neilston Route Add-On",
            "DB BR 155 Loco Add-On",
        ],
    },
    {
        "tsw_version": "TSW2",
        "bundle_id": None,
        "bundle_name": "TSW2: Starter Bundle - German Edition",
        "steam_url": "https://store.steampowered.com/app/1282590/Train_Sim_World_2/",
        "bundle_type": "Starter Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 2",
            "Hauptstrecke Hamburg - Lübeck Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW2",
        "bundle_id": None,
        "bundle_name": "TSW2: Starter Bundle - UK Edition",
        "steam_url": "https://store.steampowered.com/app/1282590/Train_Sim_World_2/",
        "bundle_type": "Starter Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 2",
            "Bakerloo Line: London Underground Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW2",
        "bundle_id": None,
        "bundle_name": "TSW2: Starter Bundle - USA Edition",
        "steam_url": "https://store.steampowered.com/app/1282590/Train_Sim_World_2/",
        "bundle_type": "Starter Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 2",
            "Peninsula Corridor: San Jose - San Francisco Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW2",
        "bundle_id": None,
        "bundle_name": "TSW2: Spirit of Steam Starter Bundle",
        "steam_url": "https://store.steampowered.com/app/1282590/Train_Sim_World_2/",
        "bundle_type": "Starter Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 2",
            "Spirit of Steam: Liverpool Lime Street - Crewe",
        ],
    },
    # ===== TRAIN SIM WORLD 3 =====
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/28149",
        "bundle_name": "Train Sim World 3: Standard Edition",
        "steam_url": "https://store.steampowered.com/bundle/28149/",
        "bundle_type": "Edition",
        "price_usd": 49.99,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 3",
            "Cajon Pass: Barstow - San Bernardino Route Add-On",
            "Schnellfahrstrecke Kassel-Würzburg Route Add-On",
            "Southeastern High Speed: London St Pancras - Ashford Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/28148",
        "bundle_name": "Train Sim World 3: Deluxe Edition",
        "steam_url": "https://store.steampowered.com/bundle/28148/",
        "bundle_type": "Edition",
        "price_usd": 69.99,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 3",
            "Cajon Pass: Barstow - San Bernardino Route Add-On",
            "Schnellfahrstrecke Kassel-Würzburg Route Add-On",
            "Southeastern High Speed: London St Pancras - Ashford Route Add-On",
            "Amtrak Acela Loco Add-On",
            "ICE 3 (BR 406) Loco Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": None,
        "bundle_name": "Train Sim World 3: New York Starter Pack",
        "steam_url": "https://store.steampowered.com/app/1944790/Train_Sim_World_3/",
        "bundle_type": "Starter Pack",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 3",
            "Northeast Corridor: New York - Trenton Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": None,
        "bundle_name": "Train Sim World 3: US Starter Pack",
        "steam_url": "https://store.steampowered.com/app/1944790/Train_Sim_World_3/",
        "bundle_type": "Starter Pack",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 3",
            "Cajon Pass: Barstow - San Bernardino Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": None,
        "bundle_name": "Train Sim World 3: Spirit of Steam Starter Pack",
        "steam_url": "https://store.steampowered.com/app/1944790/Train_Sim_World_3/",
        "bundle_type": "Starter Pack",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 3",
            "Spirit of Steam: Liverpool Lime Street - Crewe Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": None,
        "bundle_name": "Train Sim World 3: Birmingham Starter Pack",
        "steam_url": "https://store.steampowered.com/app/1944790/Train_Sim_World_3/",
        "bundle_type": "Starter Pack",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 3",
            "Birmingham Cross-City: Lichfield - Redditch Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": None,
        "bundle_name": "Train Sim World 3: Birmingham Standard Edition",
        "steam_url": "https://store.steampowered.com/app/1944790/Train_Sim_World_3/",
        "bundle_type": "Edition",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 3",
            "Birmingham Cross-City: Lichfield - Redditch Route Add-On",
            "Cajon Pass: Barstow - San Bernardino Route Add-On",
            "Schnellfahrstrecke Kassel-Würzburg Route Add-On",
            "Southeastern High Speed: London St Pancras - Ashford Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": None,
        "bundle_name": "Train Sim World 3: Deluxe Edition & Loco Bundle",
        "steam_url": "https://store.steampowered.com/app/1944790/Train_Sim_World_3/",
        "bundle_type": "Edition",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 3",
            "Cajon Pass: Barstow - San Bernardino Route Add-On",
            "Schnellfahrstrecke Kassel-Würzburg Route Add-On",
            "Southeastern High Speed: London St Pancras - Ashford Route Add-On",
            "Amtrak Acela Loco Add-On",
            "ICE 3 (BR 406) Loco Add-On",
            "DB BR 187 Loco Add-On",
        ],
    },
    # TSW3 Steam-exclusive DLC bundles
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31324",
        "bundle_name": "Train Sim World 3: US Super Bundle",
        "steam_url": "https://store.steampowered.com/bundle/31324/Train_Sim_World_3_US_Super_Bundle/",
        "bundle_type": "DLC Bundle",
        "price_usd": 142.34,
        "discount_pct": 20,
        "includes_base_game": False,
        "included_items": [
            "TSW3: Northeast Corridor: Boston - Providence Route Add-On",
            "TSW3: Sherman Hill: Cheyenne - Laramie Route Add-On",
            "TSW3: Cajon Pass: Barstow - San Bernardino Route Add-On",
            "TSW3: Union Pacific Heritage Livery Collection",
            "TSW3: Amtrak's Acela",
            "TSW3: Northeast Corridor: New York - Trenton",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31327",
        "bundle_name": "Train Sim World 3: US Passenger Bundle",
        "steam_url": "https://store.steampowered.com/bundle/31327/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "TSW3: Northeast Corridor: Boston - Providence Route Add-On",
            "TSW3: Amtrak's Acela",
            "TSW3: Northeast Corridor: New York - Trenton",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31372",
        "bundle_name": "Train Sim World: Under The Wires Bundle (TSW3)",
        "steam_url": "https://store.steampowered.com/bundle/31372/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "Southeastern High Speed: London St Pancras - Ashford Route Add-On",
            "Schnellfahrstrecke Kassel-Würzburg Route Add-On",
            "LGV Méditerranée: Marseille - Avignon Route Add-On",
            "Amtrak Acela Loco Add-On",
            "Northeast Corridor: New York - Trenton Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31328",
        "bundle_name": "Train Sim World 3: US Freight Bundle",
        "steam_url": "https://store.steampowered.com/bundle/31328/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "TSW3: Sherman Hill: Cheyenne - Laramie Route Add-On",
            "TSW3: Cajon Pass: Barstow - San Bernardino Route Add-On",
            "TSW3: Union Pacific Heritage Livery Collection",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31329",
        "bundle_name": "Train Sim World 3: Historic Journeys Bundle",
        "steam_url": "https://store.steampowered.com/bundle/31329/",
        "bundle_type": "DLC Bundle",
        "price_usd": 116.96,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "TSW3: Spirit of Steam: Liverpool Lime Street - Crewe",
            "TSW3: West Somerset Railway Route Add-On",
            "TSW3: Tees Valley Line Route Add-On",
            "TSW3: Northern Trans-Pennine: Manchester - Leeds Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31374",
        "bundle_name": "Train Sim World 3: Steam Icons Bundle",
        "steam_url": "https://store.steampowered.com/bundle/31374/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "Spirit of Steam: Liverpool Lime Street - Crewe",
            "West Somerset Railway Route Add-On",
            "Isle of Wight Route Add-On",
            "Peak Forest Railway Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31369",
        "bundle_name": "Train Sim World 3: German Passenger Bundle",
        "steam_url": "https://store.steampowered.com/bundle/31369/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "Schnellfahrstrecke Kassel-Würzburg Route Add-On",
            "Schnellfahrstrecke Köln-Aachen Route Add-On",
            "ICE 3 (BR 406) Loco Add-On",
            "ICE 3 (BR 403) Loco Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31370",
        "bundle_name": "Train Sim World 3: German Freight Bundle",
        "steam_url": "https://store.steampowered.com/bundle/31370/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "Tharandter Rampe: Dresden - Werdau Route Add-On",
            "DB BR 187 Loco Add-On",
            "DB BR 155 Loco Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31371",
        "bundle_name": "Train Sim World: Köln - Aachen & S-Bahn BR 423 Bundle",
        "steam_url": "https://store.steampowered.com/bundle/31371/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "Schnellfahrstrecke Köln-Aachen Route Add-On",
            "DB BR 423 S-Bahn Loco Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31373",
        "bundle_name": "Train Sim World 3: Great Western Bundle",
        "steam_url": "https://store.steampowered.com/bundle/31373/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "Great Western Express: London Paddington - Reading Route Add-On",
            "Class 57 'Thunderbird' Loco Add-On",
            "Class 43 HST Loco Add-On",
            "Class 80X Loco Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31375",
        "bundle_name": "Train Sim World 3: Loco Add-On Bundle",
        "steam_url": "https://store.steampowered.com/bundle/31375/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "DB BR 187 Loco Add-On",
            "DB BR 155 Loco Add-On",
            "Amtrak Acela Loco Add-On",
            "ICE 3 (BR 406) Loco Add-On",
            "Class 57 'Thunderbird' Loco Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31376",
        "bundle_name": "Train Sim World 3: Loco Add-On Bundle 2",
        "steam_url": "https://store.steampowered.com/bundle/31376/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "Class 43 HST Loco Add-On",
            "Class 80X Loco Add-On",
            "ICE 3 (BR 403) Loco Add-On",
            "DB BR 423 S-Bahn Loco Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31378",
        "bundle_name": "Train Sim World 3: Across the States Bundle",
        "steam_url": "https://store.steampowered.com/bundle/31378/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "TSW3: Horseshoe Curve: Altoona - South Fork & Cresson Route Add-On",
            "TSW3: Cane Creek: Thompson - Potash Route Add-On",
            "TSW3: Clinchfield Railroad: Elkhorn City - Dante Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/32896",
        "bundle_name": "Train Sim World 3: Class 66 Anniversary Bundle",
        "steam_url": "https://store.steampowered.com/bundle/32896/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "East Coastway: Brighton - Eastbourne & Seaford Route Add-On",
            "Southeastern High Speed: London St Pancras - Ashford Route Add-On",
            "Brighton Main Line: London Victoria - Brighton Route Add-On",
            "DB BR Class 66 Loco Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31379",
        "bundle_name": "Train Sim World 3: Midland Main Line Enhancement Bundle",
        "steam_url": "https://store.steampowered.com/bundle/31379/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": 15,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 3",
            "Midland Main Line: Leicester - Derby and Nottingham Route Add-On",
            "Rail Operations Group BR Class 37/7 Loco Add-On",
            "Rail Head Treatment Train Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31380",
        "bundle_name": "Train Sim World 3: Best of British Bundle",
        "steam_url": "https://store.steampowered.com/bundle/31380/",
        "bundle_type": "Edition",
        "price_usd": None,
        "discount_pct": 19,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 3",
            "Midland Main Line: Leicester - Derby and Nottingham Route Add-On",
            "London Commuter Route Add-On",
            "Southeastern High Speed Extended Route Add-On",
            "Northern Trans-Pennine: Manchester - Leeds Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31381",
        "bundle_name": "Train Sim World 3: High Speed Bundle",
        "steam_url": "https://store.steampowered.com/bundle/31381/",
        "bundle_type": "Edition",
        "price_usd": None,
        "discount_pct": 15,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 3",
            "LGV Méditerranée: Marseille - Avignon Route Add-On",
            "Schnellfahrstrecke Kassel-Würzburg Route Add-On",
            "Southeastern High Speed Extended Route Add-On",
            "Amtrak Acela Loco Add-On",
            "Northeast Corridor: New York - Trenton Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31382",
        "bundle_name": "Train Sim World 3: French Starter Pack",
        "steam_url": "https://store.steampowered.com/bundle/31382/",
        "bundle_type": "Starter Pack",
        "price_usd": None,
        "discount_pct": 17,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 3",
            "LGV Méditerranée: Marseille - Avignon Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31383",
        "bundle_name": "Train Sim World 3: US Starter Pack",
        "steam_url": "https://store.steampowered.com/bundle/31383/",
        "bundle_type": "Starter Pack",
        "price_usd": None,
        "discount_pct": 37,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 3",
            "Cajon Pass: Barstow - San Bernardino Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31384",
        "bundle_name": "Train Sim World 3: German Starter Pack",
        "steam_url": "https://store.steampowered.com/bundle/31384/",
        "bundle_type": "Starter Pack",
        "price_usd": None,
        "discount_pct": 37,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 3",
            "Schnellfahrstrecke Kassel-Würzburg Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW3",
        "bundle_id": "bundle/31385",
        "bundle_name": "Train Sim World 3: UK Starter Pack",
        "steam_url": "https://store.steampowered.com/bundle/31385/",
        "bundle_type": "Starter Pack",
        "price_usd": None,
        "discount_pct": 37,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 3",
            "Southeastern High Speed Extended Route Add-On",
        ],
    },
    # ===== TRAIN SIM WORLD 4 =====
    {
        "tsw_version": "TSW4",
        "bundle_id": "bundle/33906",
        "bundle_name": "Train Sim World 4: Standard Edition",
        "steam_url": "https://store.steampowered.com/bundle/33906/",
        "bundle_type": "Edition",
        "price_usd": 49.99,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 4",
            "Antelope Valley Line: Los Angeles - Lancaster Route Add-On",
            "Dresden - Riesa Route Add-On",
            "Glossop Line: Manchester - Hadfield & Glossop Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW4",
        "bundle_id": "bundle/33907",
        "bundle_name": "Train Sim World 4: Deluxe Edition",
        "steam_url": "https://store.steampowered.com/bundle/33907/",
        "bundle_type": "Edition",
        "price_usd": 69.99,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 4",
            "Antelope Valley Line: Los Angeles - Lancaster Route Add-On",
            "Dresden - Riesa Route Add-On",
            "Glossop Line: Manchester - Hadfield & Glossop Route Add-On",
            "Metrolink F125 Loco Add-On",
            "DB BR 406 ICE 3M Loco Add-On",
        ],
    },
    {
        "tsw_version": "TSW4",
        "bundle_id": "bundle/33908",
        "bundle_name": "Train Sim World 4: US Regional Edition",
        "steam_url": "https://store.steampowered.com/bundle/33908/Train_Sim_World_4_US_Regional_Edition/",
        "bundle_type": "Edition",
        "price_usd": 38.98,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 4",
            "Antelope Valley Line: Los Angeles - Lancaster Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW4",
        "bundle_id": "bundle/33909",
        "bundle_name": "Train Sim World 4: German Regional Edition",
        "steam_url": "https://store.steampowered.com/bundle/33909/",
        "bundle_type": "Edition",
        "price_usd": 23.38,
        "discount_pct": 61,
        "includes_base_game": True,
        "included_items": ["Train Sim World 4", "Dresden - Riesa Route Add-On"],
    },
    {
        "tsw_version": "TSW4",
        "bundle_id": "bundle/33910",
        "bundle_name": "Train Sim World 4: UK Regional Edition",
        "steam_url": "https://store.steampowered.com/bundle/33910/",
        "bundle_type": "Edition",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 4",
            "Glossop Line: Manchester - Hadfield & Glossop Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW4",
        "bundle_id": "bundle/35747",
        "bundle_name": "Train Sim World 4: European Expansion Bundle",
        "steam_url": "https://store.steampowered.com/bundle/35747/Train_Sim_World_4_European_Expansion_Bundle/",
        "bundle_type": "DLC Bundle",
        "price_usd": 83.96,
        "discount_pct": 20,
        "includes_base_game": False,
        "included_items": [
            "TSW4: S-Bahn Zentralschweiz: Luzern - Sursee Route Add-On",
            "TSW4: DB BR 101 Loco Add-On",
            "TSW4: Hauptstrecke Hamburg - Lübeck Route Add-On",
            "TSW4: Hauptstrecke Rhein-Ruhr: Duisburg - Bochum Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW4",
        "bundle_id": "bundle/35749",
        "bundle_name": "Train Sim World 4: USA Expansion Bundle",
        "steam_url": "https://store.steampowered.com/bundle/35749/Train_Sim_World_4_USA_Expansion_Bundle/",
        "bundle_type": "DLC Bundle",
        "price_usd": 89.55,
        "discount_pct": 20,
        "includes_base_game": False,
        "included_items": [
            "TSW4: Cajon Pass: Barstow - San Bernardino Route Add-On",
            "TSW4: Cane Creek: Thompson - Potash Route Add-On",
            "TSW4: BNSF SD70ACe Add-On",
            "TSW4: Sherman Hill: Cheyenne - Laramie Route Add-On",
            "TSW4: Santa Fe F7 Add-On",
        ],
    },
    {
        "tsw_version": "TSW4",
        "bundle_id": "bundle/35750",
        "bundle_name": "Train Sim World 4: UK Expansion Bundle",
        "steam_url": "https://store.steampowered.com/bundle/35750/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": 20,
        "includes_base_game": False,
        "included_items": [
            "TSW4: East Midlands Railway Class 158 Loco Add-On",
            "TSW4: East Midlands Railway: Nottingham - Grantham Route Add-On",
            "TSW4: London Overground Class 710 Loco Add-On",
            "TSW4: West Coast Main Line: Crewe - Manchester Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW4",
        "bundle_id": "bundle/35751",
        "bundle_name": "Train Sim World 4: German Expansion Bundle",
        "steam_url": "https://store.steampowered.com/bundle/35751/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": 20,
        "includes_base_game": False,
        "included_items": [
            "TSW4: DB BR 406 ICE 3M Loco Add-On",
            "TSW4: DB BR 187 Loco Add-On",
            "TSW4: Schnellfahrstrecke Köln-Aachen Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW4",
        "bundle_id": "bundle/37324",
        "bundle_name": "Train Sim World 4: Ultimate Collection Bundle",
        "steam_url": "https://store.steampowered.com/bundle/37324/Train_Sim_World_4_Ultimate_Collection_Bundle/",
        "bundle_type": "DLC Bundle",
        "price_usd": 344.82,
        "discount_pct": 42,
        "includes_base_game": False,
        "included_items": [
            "TSW4: Antelope Valley Line: Los Angeles - Lancaster Route Add-On",
            "TSW4: Dresden - Riesa Route Add-On",
            "TSW4: Glossop Line: Manchester - Hadfield & Glossop Route Add-On",
            "TSW4: Cajon Pass: Barstow - San Bernardino Route Add-On",
            "TSW4: Cane Creek: Thompson - Potash Route Add-On",
            "TSW4: Sherman Hill: Cheyenne - Laramie Route Add-On",
            "TSW4: S-Bahn Zentralschweiz: Luzern - Sursee Route Add-On",
            "TSW4: Hauptstrecke Hamburg - Lübeck Route Add-On",
            "TSW4: Hauptstrecke Rhein-Ruhr: Duisburg - Bochum Route Add-On",
            "TSW4: East Midlands Railway Class 158 Loco Add-On",
            "TSW4: East Midlands Railway: Nottingham - Grantham Route Add-On",
            "TSW4: London Overground Class 710 Loco Add-On",
            "TSW4: West Coast Main Line: Crewe - Manchester Route Add-On",
            "TSW4: DB BR 406 ICE 3M Loco Add-On",
            "TSW4: DB BR 187 Loco Add-On",
            "TSW4: Schnellfahrstrecke Köln-Aachen Route Add-On",
            "TSW4: DB BR 101 Loco Add-On",
            "TSW4: BNSF SD70ACe Add-On",
            "TSW4: Santa Fe F7 Add-On",
        ],
    },
    {
        "tsw_version": "TSW4",
        "bundle_id": "bundle/36840",
        "bundle_name": "Train Sim World 4: The Cargo Line Collection",
        "steam_url": "https://store.steampowered.com/bundle/36840/",
        "bundle_type": "DLC Bundle",
        "price_usd": 34.18,
        "discount_pct": 38,
        "includes_base_game": False,
        "included_items": [
            "TSW4: Cargo Line Collection Vol. 1",
            "TSW4: Cargo Line Collection Vol. 2",
            "TSW4: Cargo Line Collection Vol. 3",
        ],
    },
    {
        "tsw_version": "TSW4",
        "bundle_id": "bundle/36841",
        "bundle_name": "Train Sim World 4: Steam Icons Bundle",
        "steam_url": "https://store.steampowered.com/bundle/36841/",
        "bundle_type": "DLC Bundle",
        "price_usd": 51.60,
        "discount_pct": 68,
        "includes_base_game": False,
        "included_items": [
            "Spirit of Steam: Liverpool Lime Street - Crewe",
            "West Somerset Railway Route Add-On",
            "Isle of Wight Route Add-On",
            "Bakerloo Line: London Underground Route Add-On",
            "Sand Patch Grade: CSX Heavy Haul Route Add-On",
            "Peak Forest Railway Route Add-On",
        ],
    },
    # ===== TRAIN SIM WORLD 5 =====
    {
        "tsw_version": "TSW5",
        "bundle_id": "bundle/41825",
        "bundle_name": "Train Sim World 5: Standard Edition",
        "steam_url": "https://store.steampowered.com/bundle/41825/",
        "bundle_type": "Edition",
        "price_usd": 49.99,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 5",
            "West Coast Main Line: London Euston - Milton Keynes Route Add-On",
            "Kinzigtalbahn: Frankfurt - Gelnhausen Route Add-On",
            "San Bernardino Line: Los Angeles - San Bernardino Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW5",
        "bundle_id": "bundle/41826",
        "bundle_name": "Train Sim World 5: Deluxe Edition",
        "steam_url": "https://store.steampowered.com/bundle/41826/",
        "bundle_type": "Edition",
        "price_usd": 69.99,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 5",
            "West Coast Main Line: London Euston - Milton Keynes Route Add-On",
            "Kinzigtalbahn: Frankfurt - Gelnhausen Route Add-On",
            "San Bernardino Line: Los Angeles - San Bernardino Route Add-On",
            "Avanti West Coast Class 390 Pendolino Loco Add-On",
            "Metrolink F125 Loco Add-On (TSW5)",
        ],
    },
    {
        "tsw_version": "TSW5",
        "bundle_id": "bundle/41827",
        "bundle_name": "Train Sim World 5: Special Edition",
        "steam_url": "https://store.steampowered.com/bundle/41827/",
        "bundle_type": "Edition",
        "price_usd": 119.99,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 5",
            "West Coast Main Line: London Euston - Milton Keynes Route Add-On",
            "Kinzigtalbahn: Frankfurt - Gelnhausen Route Add-On",
            "San Bernardino Line: Los Angeles - San Bernardino Route Add-On",
            "Avanti West Coast Class 390 Pendolino Loco Add-On",
            "Metrolink F125 Loco Add-On (TSW5)",
            "Edinburgh - Glasgow Express Route Add-On",
            "Pfälzische Ludwigsbahn: Mannheim - Kaiserslautern Route Add-On",
            "West Coast Main Line: Preston - Carlisle Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW5",
        "bundle_id": "bundle/42143",
        "bundle_name": "Train Sim World 5: UK Regional Edition",
        "steam_url": "https://store.steampowered.com/bundle/42143/",
        "bundle_type": "Edition",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 5",
            "West Coast Main Line: London Euston - Milton Keynes Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW5",
        "bundle_id": "bundle/42144",
        "bundle_name": "Train Sim World 5: German Regional Edition",
        "steam_url": "https://store.steampowered.com/bundle/42144/",
        "bundle_type": "Edition",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 5",
            "Kinzigtalbahn: Frankfurt - Gelnhausen Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW5",
        "bundle_id": "bundle/42145",
        "bundle_name": "Train Sim World 5: USA Regional Edition",
        "steam_url": "https://store.steampowered.com/bundle/42145/",
        "bundle_type": "Edition",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 5",
            "San Bernardino Line: Los Angeles - San Bernardino Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW5",
        "bundle_id": "bundle/42146",
        "bundle_name": "Train Sim World 5: Festive Season Starter Bundle",
        "steam_url": "https://store.steampowered.com/bundle/42146/",
        "bundle_type": "Starter Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 5",
            "San Bernardino Line Holiday Train Add-On",
            "HKA Hopper Wagon Add-On",
            "DB BR 111 & n-Wagen Add-On",
        ],
    },
    {
        "tsw_version": "TSW5",
        "bundle_id": "bundle/47662",
        "bundle_name": "Train Sim World 5: Gameplay Add-On Bundle",
        "steam_url": "https://store.steampowered.com/bundle/47662/Train_Sim_World_5_Gameplay_AddOn_Bundle/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": 60,
        "includes_base_game": False,
        "included_items": [
            "TSW5: Metrolink Holiday Train (San Bernardino Line) Add-On",
            "TSW5: HKA Bogie Hopper Wagon Add-On",
            "TSW5: DB BR 111 & n-Wagen Add-On",
        ],
    },
    {
        "tsw_version": "TSW5",
        "bundle_id": "bundle/53103",
        "bundle_name": "Train Sim World 5: Frankfurt S-Bahn Complete Layering Bundle",
        "steam_url": "https://store.steampowered.com/bundle/53103/Train_Sim_World_5_Frankfurt_SBahn_Complete_Layering_Bundle/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "TSW5: S-Bahn Rhein-Neckar: Mannheim Hbf - Karlsruhe Route Add-On",
            "TSW5: DB BR 425 Loco Add-On",
            "TSW5: DB BR 423 S-Bahn Loco Add-On",
            "TSW5: DB BR 420 Loco Add-On",
            "TSW5: DB BR 143 Loco Add-On",
            "TSW5: DB BR 111 & n-Wagen Add-On",
        ],
    },
    {
        "tsw_version": "TSW5",
        "bundle_id": "bundle/53169",
        "bundle_name": "Train Sim World 5: Köln - Aachen Timetable Update Bundle",
        "steam_url": "https://store.steampowered.com/bundle/53169/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "TSW5: DB BR 406 ICE 3M Loco Add-On",
            "TSW5: DB BR 101 Loco Add-On",
            "TSW5: Hauptstrecke Rhein-Ruhr Route Add-On",
            "TSW5: Hauptstrecke Hamburg - Lübeck Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW5",
        "bundle_id": "bundle/54838",
        "bundle_name": "Train Sim World 5: E94 Complete Layering Bundle",
        "steam_url": "https://store.steampowered.com/bundle/54838/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "TSW5: DB BR E94 / BR 194 Loco Add-On",
            "TSW5: Schnellfahrstrecke Köln-Aachen Route Add-On",
            "TSW5: Tharandter Rampe Route Add-On",
            "TSW5: Bahnstrecke Bremen - Oldenburg Route Add-On",
            "TSW5: Hauptstrecke München - Augsburg Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW5",
        "bundle_id": "bundle/56684",
        "bundle_name": "Train Sim World 5: Dovetail Games Collection Bundle",
        "steam_url": "https://store.steampowered.com/bundle/56684/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "TSW5: Cargo Line Collection Vol. 1",
            "TSW5: Cargo Line Collection Vol. 2",
            "TSW5: Cargo Line Collection Vol. 3",
            "TSW5: Cargo Line Collection Vol. 4",
            "TSW5: Midland Main Line: Leicester - Derby and Nottingham Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW5",
        "bundle_id": "bundle/57398",
        "bundle_name": "Train Sim World 5: City Explorer Bundle",
        "steam_url": "https://store.steampowered.com/bundle/57398/Train_Sim_World_5_City_Explorer_Bundle/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "TSW5: Birmingham Cross-City Route Add-On",
            "TSW5: Class 323 Loco Add-On",
            "TSW5: Class 170 Loco Add-On",
        ],
    },
    {
        "tsw_version": "TSW5",
        "bundle_id": "bundle/57399",
        "bundle_name": "Train Sim World 5: Summertime Savings Bundle",
        "steam_url": "https://store.steampowered.com/bundle/57399/Train_Sim_World_5_Summertime_Savings_Bundle/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": 61,
        "includes_base_game": False,
        "included_items": [
            "TSW5: London Overground Suffragette Line: Gospel Oak - Barking Riverside Route Add-On",
            "TSW5: Bakerloo Line Route Add-On",
            "TSW5: West Coast Main Line: Crewe - Manchester Route Add-On",
            "TSW5: Arosalinie: Chur - Arosa Route Add-On",
            "TSW5: S-Bahn Vorarlberg: Lindau - Bregenz - Feldkirch Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW5",
        "bundle_id": "bundle/57401",
        "bundle_name": "Train Sim World 5: Intercity Connections Bundle",
        "steam_url": "https://store.steampowered.com/bundle/57401/Train_Sim_World_5_Intercity_Connections_Bundle/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "TSW5: Pfälzische Ludwigsbahn: Mannheim - Kaiserslautern Route Add-On",
            "TSW5: TGV Duplex Loco Add-On",
            "TSW5: DB BR 187 Loco Add-On",
        ],
    },
    {
        "tsw_version": "TSW5",
        "bundle_id": "bundle/57402",
        "bundle_name": "Train Sim World 5: WCML: Preston - Carlisle Essentials Bundle",
        "steam_url": "https://store.steampowered.com/bundle/57402/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "TSW5: West Coast Main Line: Preston - Carlisle Route Add-On",
            "TSW5: Class 20 Loco Add-On",
            "TSW5: Class 37 Loco Add-On",
            "TSW5: Class 40 Loco Add-On",
            "TSW5: Class 142 Pacer Add-On",
            "TSW5: Tees Valley Line Route Add-On",
            "TSW5: Northern Trans-Pennine Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW5",
        "bundle_id": "bundle/57403",
        "bundle_name": "Train Sim World 5: Autumn Leaves Bundle",
        "steam_url": "https://store.steampowered.com/bundle/57403/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "TSW5: Rail Head Treatment Train (RHTT) Add-On",
            "TSW5: East Coastway: Brighton - Eastbourne & Seaford Route Add-On",
            "TSW5: Harlem Line: Grand Central Terminal - Southeast Route Add-On",
            "TSW5: Bahnstrecke Bremen - Oldenburg Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW5",
        "bundle_id": "bundle/55230",
        "bundle_name": "Train Sim World 5: Mannheim Connections Bundle",
        "steam_url": "https://store.steampowered.com/bundle/55230/",
        "bundle_type": "DLC Bundle",
        "price_usd": 148.44,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "TSW5: Pfälzische Ludwigsbahn: Mannheim - Kaiserslautern Route Add-On",
            "TSW5: S-Bahn Rhein-Neckar: Mannheim Hbf - Karlsruhe Route Add-On",
            "TSW5: DB BR 425 Loco Add-On",
            "TSW5: TGV Duplex Loco Add-On",
            "TSW5: DB BR 187 Loco Add-On",
            "TSW5: DB BR 111 & n-Wagen Add-On",
        ],
    },
    # ===== TRAIN SIM WORLD 6 =====
    {
        "tsw_version": "TSW6",
        "bundle_id": "bundle/64100",
        "bundle_name": "Train Sim World 6: Standard Edition",
        "steam_url": "https://store.steampowered.com/app/3656800/Train_Sim_World_6/",
        "bundle_type": "Edition",
        "price_usd": 39.99,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 6",
            "Avanti West Coast: London Euston - Liverpool Route Add-On",
            "S-Bahn Zentralschweiz: Luzern - Sursee Route Add-On",
            "NJ Transit: Raritan Valley Line Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW6",
        "bundle_id": "bundle/64101",
        "bundle_name": "Train Sim World 6: Deluxe Edition",
        "steam_url": "https://store.steampowered.com/app/3656800/Train_Sim_World_6/",
        "bundle_type": "Edition",
        "price_usd": 59.99,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 6",
            "Avanti West Coast: London Euston - Liverpool Route Add-On",
            "S-Bahn Zentralschweiz: Luzern - Sursee Route Add-On",
            "NJ Transit: Raritan Valley Line Route Add-On",
            "Avanti West Coast Class 805 Loco Add-On",
            "DB Vectron BR 193 Loco Add-On",
        ],
    },
    {
        "tsw_version": "TSW6",
        "bundle_id": "bundle/64102",
        "bundle_name": "Train Sim World 6: Special Edition",
        "steam_url": "https://store.steampowered.com/app/3656800/Train_Sim_World_6/",
        "bundle_type": "Edition",
        "price_usd": 119.99,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 6",
            "Avanti West Coast: London Euston - Liverpool Route Add-On",
            "S-Bahn Zentralschweiz: Luzern - Sursee Route Add-On",
            "NJ Transit: Raritan Valley Line Route Add-On",
            "Avanti West Coast Class 805 Loco Add-On",
            "DB Vectron BR 193 Loco Add-On",
            "West Coast Main Line: London Euston - Milton Keynes Route Add-On (TSW6 Compatible)",
            "San Bernardino Line: Los Angeles - San Bernardino Route Add-On (TSW6 Compatible)",
            "Kinzigtalbahn: Frankfurt - Gelnhausen Route Add-On (TSW6 Compatible)",
        ],
    },
    {
        "tsw_version": "TSW6",
        "bundle_id": "bundle/64103",
        "bundle_name": "Train Sim World 6: Thomas & Friends Edition",
        "steam_url": "https://store.steampowered.com/app/3656800/Train_Sim_World_6/",
        "bundle_type": "Edition",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 6",
            "Avanti West Coast: London Euston - Liverpool Route Add-On",
            "S-Bahn Zentralschweiz: Luzern - Sursee Route Add-On",
            "NJ Transit: Raritan Valley Line Route Add-On",
            "Thomas & Friends: Visit the West Somerset Railway Add-On",
            "Thomas & Friends: 80th Anniversary Expansion",
        ],
    },
    {
        "tsw_version": "TSW6",
        "bundle_id": "bundle/65800",
        "bundle_name": "Train Sim World 6: UK Regional Edition",
        "steam_url": "https://store.steampowered.com/bundle/65800/",
        "bundle_type": "Edition",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 6",
            "Avanti West Coast: London Euston - Liverpool Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW6",
        "bundle_id": "bundle/65801",
        "bundle_name": "Train Sim World 6: German Regional Edition",
        "steam_url": "https://store.steampowered.com/bundle/65801/",
        "bundle_type": "Edition",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 6",
            "S-Bahn Zentralschweiz: Luzern - Sursee Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW6",
        "bundle_id": "bundle/65802",
        "bundle_name": "Train Sim World 6: US Regional Edition",
        "steam_url": "https://store.steampowered.com/bundle/65802/",
        "bundle_type": "Edition",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": True,
        "included_items": [
            "Train Sim World 6",
            "NJ Transit: Raritan Valley Line Route Add-On",
        ],
    },
    {
        "tsw_version": "TSW6",
        "bundle_id": "bundle/66609",
        "bundle_name": "Train Sim World 6: Great Western Express Remaster Essentials Bundle",
        "steam_url": "https://store.steampowered.com/bundle/66609/Train_Sim_World_6_Great_Western_Express_Remaster_Essentials_Bundle/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "TSW6: Great Western Express: London Paddington - Reading Route Add-On (Remastered)",
            "TSW6: Class 43 HST Loco Add-On",
            "TSW6: Class 57 'Thunderbird' Loco Add-On",
            "TSW6: Class 802 IET Loco Add-On",
        ],
    },
    {
        "tsw_version": "TSW6",
        "bundle_id": "bundle/66610",
        "bundle_name": "Train Sim World 6: Avanti West Coast Class 805 Essentials Bundle",
        "steam_url": "https://store.steampowered.com/bundle/66610/",
        "bundle_type": "DLC Bundle",
        "price_usd": None,
        "discount_pct": None,
        "includes_base_game": False,
        "included_items": [
            "TSW6: Avanti West Coast Class 805 Loco Add-On",
            "TSW6: Avanti West Coast: London Euston - Liverpool Route Add-On",
            "TSW6: West Coast Main Line: London Euston - Milton Keynes Route Add-On",
        ],
    },
]

# --- Save JSON ---
json_output = json.dumps(bundles, indent=2, ensure_ascii=False)
with open("./.temp/tsw_bundles.json", "w", encoding="utf-8") as f:
    f.write(json_output)

# --- Save CSV ---
# For CSV, included_items will be a semicolon-separated string
with open("./.temp/tsw_bundles.csv", "w", newline="", encoding="utf-8") as f:
    fieldnames = [
        "tsw_version",
        "bundle_id",
        "bundle_name",
        "steam_url",
        "bundle_type",
        "price_usd",
        "discount_pct",
        "includes_base_game",
        "included_items",
    ]
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    for b in bundles:
        row = dict(b)
        row["included_items"] = " | ".join(b["included_items"])
        writer.writerow(row)

print(f"Done! Written {len(bundles)} bundles.")
print("Breakdown:")
from collections import Counter

c = Counter(b["tsw_version"] for b in bundles)
for k in ["TSW1", "TSW2020", "TSW2", "TSW3", "TSW4", "TSW5", "TSW6"]:
    print(f"  {k}: {c.get(k,0)} bundles")
